const express = require('express');
const axios = require('axios');
const sharp = require('sharp');
const http = require('http');
const https = require('https');

const app = express();

// إعداد عميل Axios مع تفعيل keepAlive لسرعة الطلبات
const httpAgent = new http.Agent({ keepAlive: true, maxSockets: 50 });
// تجاهل أخطاء شهادات SSL التي تسبب رفض روابط المانجا
const httpsAgent = new https.Agent({ 
    keepAlive: true, 
        maxSockets: 50,
            rejectUnauthorized: false 
            });

            const axiosInstance = axios.create({
                // رفع وقت الانتظار إلى 15 ثانية لاستيعاب الخوادم البطيئة والصور الكبيرة
                    timeout: 15000, 
                        responseType: 'arraybuffer',
                            httpAgent,
                                httpsAgent,
                                    headers: {
                                            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
                                                    'Accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8',
                                                            'Accept-Language': 'en-US,en;q=0.9', // إضافة هذا الرأس لتفادي حظر بعض الخوادم
                                                                    'Accept-Encoding': 'gzip, deflate, br'
                                                                        }
                                                                        });

                                                                        // إنتاج صورة سوداء بديلة بحجم متناهي الصغر (1 كيلوبايت) لمنع الـ Loop
                                                                        async function getFallbackImage() {
                                                                            return await sharp({
                                                                                    create: {
                                                                                                width: 400,
                                                                                                            height: 600,
                                                                                                                        channels: 3,
                                                                                                                                    background: { r: 15, g: 15, b: 15 } // لون رمادي داكن / أسود
                                                                                                                                            }
                                                                                                                                                })
                                                                                                                                                    .jpeg({ quality: 10 })
                                                                                                                                                        .toBuffer();
                                                                                                                                                        }

                                                                                                                                                        app.get('/', async (req, res) => {
                                                                                                                                                            const imageUrl = req.query.url;
                                                                                                                                                                if (!imageUrl) {
                                                                                                                                                                        return res.status(200).send('v1.1-MaxPerformance Proxy Active');
                                                                                                                                                                            }

                                                                                                                                                                                try {
                                                                                                                                                                                        // 1. جلب الصورة من المصدر الأصلي
                                                                                                                                                                                                const response = await axiosInstance.get(imageUrl, {
                                                                                                                                                                                                            headers: {
                                                                                                                                                                                                                            'Referer': new URL(imageUrl).origin
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                        // 2. معالجة وتحديد متغيرات الضغط
                                                                                                                                                                                                                                                                const rawQuality = req.query.q || req.query.quality || req.query.l || req.headers['x-image-quality'];
                                                                                                                                                                                                                                                                        let quality = rawQuality ? parseInt(rawQuality, 10) : 40;

                                                                                                                                                                                                                                                                                if (isNaN(quality)) quality = 40;
                                                                                                                                                                                                                                                                                        quality = Math.max(1, Math.min(100, quality));

                                                                                                                                                                                                                                                                                                const isGrayscale = req.query.bw === '1' || req.query.bw === 'true' || req.query.grayscale === '1';
                                                                                                                                                                                                                                                                                                        const targetWidth = Math.round(450 + (quality / 100) * 900);

                                                                                                                                                                                                                                                                                                                // 3. بناء خط المعالجة (Sharp Pipeline)
                                                                                                                                                                                                                                                                                                                        let pipeline = sharp(response.data, { failOn: 'none', fastShrinkOnLoad: true })
                                                                                                                                                                                                                                                                                                                                    .rotate()
                                                                                                                                                                                                                                                                                                                                                .resize({
                                                                                                                                                                                                                                                                                                                                                                width: targetWidth,
                                                                                                                                                                                                                                                                                                                                                                                fit: 'inside',
                                                                                                                                                                                                                                                                                                                                                                                                withoutEnlargement: true,
                                                                                                                                                                                                                                                                                                                                                                                                                fastShrinkOnLoad: true
                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                    if (isGrayscale) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                pipeline = pipeline.grayscale();
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                pipeline = pipeline.jpeg({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            quality: quality,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        mozjpeg: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    progressive: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                chromaSubsampling: isGrayscale ? '4:2:0' : (quality < 50 ? '4:2:0' : '4:4:4'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            trellisQuantisation: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        overshootDeringing: true
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const compressedBuffer = await pipeline.toBuffer();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res.set({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'Content-Type': 'image/jpeg',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'Content-Length': compressedBuffer.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'Cache-Control': 'public, max-age=31536000, immutable',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'X-Proxy-Version': '1.1-MaxPerformance'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return res.status(200).send(compressedBuffer);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // طباعة الرابط الذي فشل لمعرفة السبب بدقة في السجلات
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error(`Image Fetch Error [${imageUrl}]:`, err.message);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // إرجاع الصورة السوداء الخفيفة فوراً لمنع التكرار وإغلاق الطلب بسلام
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const fallbackBuffer = await getFallbackImage();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.set({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'Content-Type': 'image/jpeg',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'Content-Length': fallbackBuffer.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'Cache-Control': 'public, max-age=86400', // حفظ في الكاش ليوم واحد فقط
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'X-Proxy-Status': 'Fallback-Image'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return res.status(200).send(fallbackBuffer);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (fallbackErr) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return res.status(500).send('Critical Error');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    module.exports = app;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
