const express = require('express');
const axios = require('axios');
const sharp = require('sharp');
const http = require('http');
const https = require('https');

const app = express();

const httpAgent = new http.Agent({ keepAlive: true, maxSockets: 50 });
const httpsAgent = new https.Agent({ 
    keepAlive: true, 
        maxSockets: 50,
            rejectUnauthorized: false
            });

            const axiosInstance = axios.create({
                timeout: 15000,
                    responseType: 'arraybuffer',
                        httpAgent,
                            httpsAgent,
                                headers: {
                                        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
                                                'Accept': 'image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8',
                                                        'Accept-Language': 'en-US,en;q=0.9'
                                                            }
                                                            });

                                                            const COVER_PATTERNS = [
                                                                'cover', 'thumb', 'poster', 'avatar', 'banner', 'front',
                                                                    'thumbnail', 'title', 'card', 'preview', 'header', 'series',
                                                                        'comic_', 'manga_', 'book_', 'jacket', 'artwork', '_small',
                                                                            '_medium', '300x', '250x', '200x', '.thumb.', '-thumb-',
                                                                                '/co/', '/c/', '/p/', 'view', 'item', 'cover_url', 'thumbnail_url'
                                                                                ];

                                                                                async function getFallbackImage() {
                                                                                    return await sharp({
                                                                                            create: {
                                                                                                        width: 400,
                                                                                                                    height: 600,
                                                                                                                                channels: 3,
                                                                                                                                            background: { r: 15, g: 15, b: 15 }
                                                                                                                                                    }
                                                                                                                                                        })
                                                                                                                                                            .jpeg({ quality: 10 })
                                                                                                                                                                .toBuffer();
                                                                                                                                                                }

                                                                                                                                                                function checkIfCover(url) {
                                                                                                                                                                    if (!url) return false;
                                                                                                                                                                        const lowerUrl = url.toLowerCase();
                                                                                                                                                                            return COVER_PATTERNS.some(pattern => lowerUrl.includes(pattern));
                                                                                                                                                                            }

                                                                                                                                                                            // دالة معالجة الصور
                                                                                                                                                                            async function handleImageRequest(imageUrl, req, res) {
                                                                                                                                                                                try {
                                                                                                                                                                                        const response = await axiosInstance.get(imageUrl, {
                                                                                                                                                                                                    headers: { 'Referer': new URL(imageUrl).origin }
                                                                                                                                                                                                            });

                                                                                                                                                                                                                    const isCover = checkIfCover(imageUrl);
                                                                                                                                                                                                                            let targetWidth, quality;

                                                                                                                                                                                                                                    if (isCover) {
                                                                                                                                                                                                                                                targetWidth = 280; 
                                                                                                                                                                                                                                                            quality = 20;     
                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                const rawQuality = req.query.q || req.query.quality || req.query.l || req.headers['x-image-quality'];
                                                                                                                                                                                                                                                                                            quality = rawQuality ? parseInt(rawQuality, 10) : 40;
                                                                                                                                                                                                                                                                                                        if (isNaN(quality)) quality = 40;
                                                                                                                                                                                                                                                                                                                    quality = Math.max(1, Math.min(100, quality));
                                                                                                                                                                                                                                                                                                                                targetWidth = Math.round(450 + (quality / 100) * 900);
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                const isGrayscale = req.query.bw === '1' || req.query.bw === 'true' || req.query.grayscale === '1';

                                                                                                                                                                                                                                                                                                                                                        let pipeline = sharp(response.data, { failOn: 'none', fastShrinkOnLoad: true })
                                                                                                                                                                                                                                                                                                                                                                    .rotate()
                                                                                                                                                                                                                                                                                                                                                                                .resize({ width: targetWidth, fit: 'inside', withoutEnlargement: true, fastShrinkOnLoad: true });

                                                                                                                                                                                                                                                                                                                                                                                        if (isGrayscale && !isCover) pipeline = pipeline.grayscale();

                                                                                                                                                                                                                                                                                                                                                                                                pipeline = pipeline.jpeg({
                                                                                                                                                                                                                                                                                                                                                                                                            quality: quality,
                                                                                                                                                                                                                                                                                                                                                                                                                        mozjpeg: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                    progressive: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                chromaSubsampling: isCover ? '4:2:0' : (isGrayscale ? '4:2:0' : (quality < 50 ? '4:2:0' : '4:4:4')),
                                                                                                                                                                                                                                                                                                                                                                                                                                                            trellisQuantisation: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        overshootDeringing: true
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const compressedBuffer = await pipeline.toBuffer();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res.set({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'Content-Type': 'image/jpeg',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'Content-Length': compressedBuffer.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'Cache-Control': 'public, max-age=31536000, immutable',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'X-Proxy-Version': '1.3-SmartProxy',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'X-Image-Type': isCover ? 'Cover' : 'Chapter'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return res.status(200).send(compressedBuffer);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const fallbackBuffer = await getFallbackImage();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res.set({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'Content-Type': 'image/jpeg',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'Content-Length': fallbackBuffer.length,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'Cache-Control': 'public, max-age=86400',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'X-Proxy-Status': 'Fallback-Image'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return res.status(200).send(fallbackBuffer);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // 1. استقبال الطلبات عبر البرامتر ?url=
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    app.get('/', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const imageUrl = req.query.url;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!imageUrl) return res.status(200).send('v1.3-SmartProxy Active');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return await handleImageRequest(imageUrl, req, res);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 2. استقبال الطلبات المباشرة المعكوسة (التي ترسلها الإضافات أو البروكسيات)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.get('/:protocol(http|https)/*SetURL', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const fullUrl = req.params.protocol + '://' + req.params[0] + (req.url.includes('?') ? req.url.substring(req.url.indexOf('?')) : '');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return await handleImageRequest(fullUrl, req, res);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        module.exports = app;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        